Fix range when no range in osim
pyomeca/osim_to_biomod pull request #4
Opened 2023-02-10 20:04 UTC by aceglia

2023-10-24 22:34 UTC, Ipuch commented
I think I need this PR to be merged ! :)

2023-10-25 14:13 UTC, pariterre requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/osim_to_biomod/4)* status: all files reviewed, 1 unresolved discussion (waiting on @aceglia)

___
*[`osim_to_biomod/converter.py` line 419 at r1](https://reviewable.io/reviews/pyomeca/osim_to_biomod/4#-NhbATu4-xpeAF5XY33z:-NhbATu4-xpeAF5XY34-:b-wtdgh) ([raw file](https://github.com/pyomeca/osim_to_biomod/blob/94fc8f4ceea79d87da2ed58b69da22deb8c14bbb/osim_to_biomod/converter.py#L419)):*
> ```Python
> 
>                 for q, qrange in enumerate(q_range):
>                     if qrange:
> ```

The difference is subtle between "q_range" and "qrange" "ranges" or "q_ranges" for the former?


<!-- Sent from Reviewable.io -->

2025-04-24 21:20 UTC, pariterre commented
@aceglia I suggest that further development to be done on https://github.com/pyomeca/biobuddy which implements similar stuff in a more generic approach

2025-04-24 21:24 UTC, aceglia commented
Yes I know I just needed a quick fix. I didn't even remember that I had an open PR.

2025-04-24 21:27 UTC, closed without merging